sbs/urls.py
    url(r'etut-proje/proje-duzenle/personel/(?P<pk>\d+)$', EPProjectViews.edit_project_personel, name='proje-incele-personel'),
    url(r'etut-proje/projeler/dokumanekle$', EPProjectViews.dokumanAdd, name='dokumanAdd'),

    url(r'etut-proje/employess/$', EPProjectViews.return_projects_mimar, name='mimarlar'),

    url(r'etut-proje/proje-pdf/(?P<pk>\d+)$', PdfView.edit_project_pdf, name='proje-pdf'),

    url(r'etut-proje/proje-pdf/teknik/(?P<pk>\d+)$', PdfView.edit_project_pdf_teknik, name='proje-pdf-teknik'),
    url(r'etut-proje/proje-pdf/personel/(?P<pk>\d+)$', PdfView.edit_project_pdf_personel, name='proje-pdf-personel'),
    url(r'etut-proje/proje-excel/(?P<pk>\d+)$', PdfView.edit_project_excel, name='proje-excel'),

    url(r'etut-proje/isTanimiListesi/$', EPProjectViews.return_employeetitles, name='istanimiListesi'),
    url(r'etut-proje/isTanimi/sil/(?P<pk>\d+)$', EPProjectViews.delete_employeetitle,
        name='unvan-sil'),
    # url(r'etut-proje/görev-duzenle/(?P<pk>\d+)$', EPProjectViews.edit_employeetitle,
    #     name='unvan-duzenle'),
    url(r'etut-proje/proje-personel-ekle/(?P<pk>\d+)$',
        EPProjectViews.add_employee_to_project, name='proje-personel-ekle'),
    url(r'etut-proje/personel/$', EPProjectViews.return_personel_dashboard, name='personel'),

    url(r'log/log-kayıtlari/$', LogViews.return_log,
        name='logs'),



    url(r'etut-proje/proje-personel-guncelle/(?P<pk>\d+)$',
        EPProjectViews.update_employee_to_project, name='proje-personel-guncelle'),
    url(r'etut-proje/proje-altproje-guncelle/(?P<pk>\d+)$',
        EPProjectViews.update_subcompany_to_project, name='proje-altproje-guncelle'),

    url(r'etut-proje/proje-altProjeFirma/(?P<pk>\d+)$',
        EPProjectViews.update_subcompany_information_to_project, name='proje-altproje-firmaBilgileri'),

    url(r'etut-proje/proje-altproje/(?P<pk>\d+)$',
        EPProjectViews.project_subfirma, name='proje-altfirma-ekle'),

    url(r'etut-proje/proje-hakedis-guncelle/(?P<pk>\d+)$',
        EPProjectViews.update_vest_to_project, name='proje-hakedis-guncelle'),



    url(r'etut-proje/proje-personel-sil/(?P<project_pk>\d+)/(?P<employee_pk>\d+)/$',
        EPProjectViews.delete_employee_from_project,
        name='proje-personel-kaldir'),

    url(r'etut-proje/proje-altfirma-sil/(?P<project_pk>\d+)/(?P<employee_pk>\d+)/$',
        EPProjectViews.delete_subcompany_project,
        name='proje-altfirma-kaldir'),
    url(r'etut-proje/proje-ihtiyac-ekle/(?P<pk>\d+)$',
        EPProjectViews.add_requirement_to_project, name='proje-ihtiyac-ekle'),
    url(r'etut-proje/proje-hakedis-ekle/(?P<pk>\d+)$',
        EPProjectViews.add_vest_to_project, name='proje-hakedis-ekle'),

    url(r'etut-proje/proje-ihtiyac-guncelle/(?P<pk>\d+)$',
        EPProjectViews.update_requirement_to_project, name='proje-ihtiyac-güncelle'),

    url(r'etut-proje/proje-ihtiyac-sil/(?P<project_pk>\d+)/(?P<employee_pk>\d+)/$',
        EPProjectViews.delete_requirement_from_project,
        name='proje-ihtiyac-kaldir'),
    url(r'etut-proje/proje-asama-ekle/(?P<pk>\d+)$',
        EPProjectViews.add_phase_to_project, name='proje-asama-ekle'),

    url(r'etut-proje/proje-asama-guncelle/(?P<pk>\d+)$',
        EPProjectViews.update_phase_to_project, name='proje-asama-guncelle'),



    url(r'etut-proje/proje-asama-sil/(?P<project_pk>\d+)/(?P<employee_pk>\d+)/$',
        EPProjectViews.delete_phase_from_project,
        name='proje-asama-kaldir'),
    url(r'etut-proje/proje-gorus-sil/(?P<project_pk>\d+)/(?P<employee_pk>\d+)/$',
        EPProjectViews.delete_ofters_from_project,
        name='proje-gorus-kaldir'),

    url(r'etut-proje/proje-hakedis-sil/(?P<project_pk>\d+)/(?P<employee_pk>\d+)/$',
        EPProjectViews.delete_vest_from_project,
        name='proje-hakedis-kaldir'),
    url(r'etut-proje/proje-oneri-ekle/(?P<pk>\d+)$',
        EPProjectViews.add_offer_to_project, name='proje-oneri-ekle'),
    # ajax ile personel ekleme
    url(r'etut-proje/proje-personel-bilgi/$',
        EPProjectViews.personel_list, name='personel-bilgi'),
    url(r'etut-proje/proje-ihtiyac-bilgi/$',
        EPProjectViews.ihtiyac_list, name='ihtiyac-bilgi'),
    url(r'etut-proje/proje-asama-bilgi/$',
        EPProjectViews.asama_list, name='asama-bilgi'),
    url(r'etut-proje/proje-town/$', EPProjectViews.town, name='ilce-bilgi'),
    url(r'etut-proje/proje/delete/(?P<pk>\d+)$', EPProjectViews.deleteReferee,
        name='proje-delete'),
    url(r'etut-proje/proje-dokuman-sil/(?P<project_pk>\d+)/(?P<employee_pk>\d+)/$',
        EPProjectViews.delete_document_project,
        name='proje-dokuman-kaldir'),

    url(r'etut-proje/proje-needdokuman-sil/(?P<project_pk>\d+)/(?P<employee_pk>\d+)/$',
        EPProjectViews.delete_needdocument_project,
        name='proje-ihtiyacDokuman-kaldir'),


    url(r'personel/personeller/$', EmployeeViews.return_employees, name='personeller'),
    url(r'personel/personeller/hepsi/$', EmployeeViews.return_employees_all, name='personeller-all'),
    url(r'personel/personel-ekle/$', EmployeeViews.add_employee, name='personel-ekle'),
    url(r'personel/personel-duzenle/(?P<pk>\d+)$', EmployeeViews.edit_employee, name='personel-duzenle'),
    url(r'personel/unvanListesi/$', EmployeeViews.return_workdefinitionslist, name='unvanlistesi'),
    url(r'personel/istanimi/sil/(?P<pk>\d+)$', EmployeeViews.delete_workdefinition,
        name='istanimi-sil'),
    url(r'personel/isTanimi-duzenle/(?P<pk>\d+)$', EmployeeViews.edit_workdefinition,
        name='istanimi-duzenle'),
    url(r'personel/Unvan-duzenle/(?P<pk>\d+)$', EmployeeViews.edit_workdefinitionUnvan,
        name='unvan-duzenle'),
    url(r'personel/personel-profil-guncelle/$', EmployeeViews.updateRefereeProfile,
        name='personel-profil-guncelle'),


#     pdf test

    url(r'pdf/$',PdfView.return_pdf, name='pdf'),
    url(r'pdf2/$', PdfView.html_to_pdf_view, name='pdf2'),
    url(r'pdf3/$', PdfView.return_pdf2, name='pdf3'),





    url(r'excel/$',PdfView.return_excel, name='excel'),
    url(r'excel2/$', PdfView.return_excel_row, name='excel2'),
    url(r'excel/personeller$', PdfView.return_excel_row_personel, name='excel-personel'),



     # technical
    url(r'etut-proje/teknik/$', TechnicalViews.return_technical_dashboard, name='anasayfa-teknik'),
    url(r'etut-proje/projeler/teknik$', TechnicalViews.return_projects, name='projeler-teknik'),
    url(r'etut-proje/proje-duzenle/teknik/(?P<pk>\d+)$', TechnicalViews.edit_project_personel,
        name='proje-incele-teknik'),
    url(r'etut-proje/personel-profil-guncelle/$', TechnicalViews.updateRefereeProfile,
        name='teknik-profil-guncelle'),
    url(r'teknik/personeller/$', TechnicalViews.return_employees, name='personeller-teknik'),
    url(r'teknik/personel-ekle/$', TechnicalViews.add_employee, name='personel-ekle-teknik'),

    url(r'notification/notification-all/$', NotificationView.notification, name='bildirimler'),

    url(r'message/$', DashboardViews.return_message,
        name='message'),

    path(r'message/api/v1/', include(router.urls)),

    # url(r'hello/$', TestList.as_view(), name='hello'),

    #     company
    url(r'company/company-add/$', CompanyView.return_add_Company, name='company-add'),
    url(r'company/company-list/$', CompanyView.return_list_Company, name='company-list'),
    url(r'company/company-update/(?P<pk>\d+)$', CompanyView.return_update_Company, name='company-update'),

    url(r'destek-talep-listesi', ClaimView.return_claim, name='destek-talep-listesi'),
    url(r'destek/Destekekle', ClaimView.claim_add, name='destek-talep-ekle'),
    url(r'destek/sil/(?P<pk>\d+)$', ClaimView.claim_delete, name='destek-delete'),
    url(r'destek/guncelle/(?P<pk>\d+)$', ClaimView.claim_update, name='destek-guncelle'),

    url(r'menu', ClaimView.menu, name='destek-talep-menu'),

    #     gayrimenkul eklemeler
    #     tasinamaz ekle

    url(r'gayrimenkul/tasinmaz-ekle/$', GtasinamazView.add_tasinmaz, name='tasinmaz-add'),
    url(r'gayrimenkul/tasinmaz-duzenle/(?P<pk>\d+)$', GtasinamazView.edit_tasinmaz, name='tasinmaz-duzenle'),
    url(r'gayrimenkul/tasinmazlar/$', GtasinamazView.tasinmaz_list, name='tasinmaz-list'),
    url(r'gayrimenkul/tasinmaz/delete/(?P<pk>\d+)$', GtasinamazView.delete_tasinmaz,
        name='tasinmaz-delete'),

    url(r'gayrimenkul/tasimaz-oneri-ekle/(?P<pk>\d+)$',
        GtasinamazView.add_offer_to_project, name='tasinmaz-oneri-ekle'),
    url(r'gayrimenkul/tasimaz-gorus-sil/(?P<project_pk>\d+)/(?P<employee_pk>\d+)/$',
        GtasinamazView.delete_ofters_from_project, name='tasinmaz-gorus-kaldir'),

    url(r'gayrimenkul/kurum-ekle/$', GtasinamazView.add_kurum, name='kurum-add'),
    url(r'gayrimenkul/kurum-duzenle/(?P<pk>\d+)$', GtasinamazView.edit_kurum, name='kurum-duzenle'),

    # url(r'gayrimenkul/teskilat/olustur/$', GtasinamazView.add_teskilat_olustur, name='teskilat-add-olustur'),
    url(r'gayrimenkul/teskilat-ekle/$', GtasinamazView.add_teskilat, name='teskilat-add'),
    url(r'gayrimenkul/teskilat-duzenle/(?P<pk>\d+)$', GtasinamazView.edit_teskilat, name='teskilat-duzenle'),
    url(r'gayrimenkul/teskilat/listesi/$', GtasinamazView.list_teskilat, name='teskilat-listesi'),
    url(r'gayrimenkul/birimEkle/(?P<pk>\d+)$', GtasinamazView.project_subfirma, name='proje-birim-ekle'),
    url(r'gayrimenkul/tasinmaz-birim-sil/(?P<tasinmaz>\d+)/(?P<kurum>\d+)/$', GtasinamazView.delete_birim_tasinmaz,
        name='tasinmaz-birim-kaldir'),

    url(r'gayrimenkul/tasinmaz-binaAltturu/$', GtasinamazView.tasimazAltTur, name='binaAlttur-bilgi'),

    url(r'gayrimenkul/teskilat-bolgeEkle/$', GtasinamazView.BolgeAdd, name='bolge-add'),
    url(r'gayrimenkul/teskilat-BolgeList/$', GtasinamazView.BolgeList, name='bolge-list'),
    url(r'gayrimenkul/teskilat-bolgeGuncelle/(?P<pk>\d+)$', GtasinamazView.bolgeUpdate, name='bolge-duzenle'),

    url(r'gayrimenkul/maps1/$', GtasinamazView.mapscitryone, name='il-selectone'),

sbs/models/Athlete.py
from django.contrib.auth.models import User
from django.db import models

from sbs.models.Communication import Communication
from sbs.models.Level import Level
from sbs.models.License import License
from sbs.models.Person import Person


class Athlete(models.Model):
    person = models.OneToOneField(Person, on_delete=models.CASCADE, db_column='person')
    communication = models.OneToOneField(Communication, on_delete=models.CASCADE, db_column='communication')
    user = models.OneToOneField(User, on_delete=models.CASCADE, db_column='user')
    belts = models.ManyToManyField(Level)
    licenses = models.ManyToManyField(License)
    creationDate = models.DateTimeField(auto_now_add=True)
    operationDate = models.DateTimeField(auto_now=True)
    kobilid = models.IntegerField(null=True, blank=True, default=2)

    def __str__(self):
        return '%s %s' % (self.user.first_name, self.user.last_name)

    class Meta:
        ordering = ['pk']
        default_permissions = ()
        db_table = 'athlete'
        managed = False

sbs/models/BeltExam.py
from django.db import models

from sbs.models import Coach, Athlete, SportsClub
from sbs.models.EnumFields import EnumFields


class BeltExam(models.Model):
    BANK = 'Banka'
    POSTA = 'Posta'
    PAYMENT_CHOICES = (
        (BANK, 'Banka'),
        (POSTA, 'Posta'),
    )
    WAITED = 'Beklemede'
    APPROVED = 'Onaylandı'
    PROPOUND = 'Onaya Gönderildi'
    DENIED = 'Reddedildi'

    STATUS_CHOICES = (
        (APPROVED, 'Onaylandı'),
        (PROPOUND, 'Onaya Gönderildi'),
        (DENIED, 'Reddedildi'),
        (WAITED, 'Beklemede'),
    )

    creationDate = models.DateTimeField(auto_now_add=True)
    modificationDate = models.DateTimeField(auto_now=True)
    examDate = models.DateField(null=False, blank=False)

    coachs=models.ManyToManyField(Coach)


    paymentType = models.CharField(max_length=128, verbose_name='Ödeme Şekli', choices=PAYMENT_CHOICES, default=BANK)
    dekont = models.FileField(upload_to='dekont/', null=False, blank=False, verbose_name='Dekont ')
    dekontDate = models.DateField(null=True, blank=True)
    dekontDescription = models.CharField(max_length=255, null=True, blank=True)
    athletes = models.ManyToManyField(Athlete)
    status = models.CharField(max_length=128, verbose_name='Onay Durumu', choices=STATUS_CHOICES, default=WAITED)
    sportClub = models.ForeignKey(SportsClub, on_delete=models.CASCADE, null=False, blank=False)
    description = models.CharField(max_length=255, null=True, blank=True)
    branch = models.CharField(max_length=128, choices=EnumFields.BRANCH.value, null=False, blank=False)
    kobilid = models.IntegerField(null=True, blank=True, default=2)


    class Meta:
        default_permissions = ()

sbs/models/Branch.py
from django.db import models


class Branch(models.Model):
    name = models.CharField(blank=True, null=True, max_length=120, verbose_name='Branş Adı')
    creationDate = models.DateTimeField(auto_now_add=True)
    modificationDate = models.DateTimeField(auto_now=True)
    kobilid = models.IntegerField(null=True, blank=True, default=2)

    def __str__(self):
        return '%s ' % self.name

    class Meta:
        default_permissions = ()

sbs/models/CategoryItem.py
from django.db import models

from sbs.models.EnumFields import EnumFields


class CategoryItem(models.Model):
    name = models.CharField(blank=False, null=False, max_length=255)
    forWhichClazz = models.CharField(blank=False, null=False, max_length=255)
    parent = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True)
    branch = models.CharField(max_length=128, choices=EnumFields.BRANCH.value,null=True,blank=True,verbose_name='Seçiniz')
    isFirst = models.BooleanField()
    creationDate = models.DateTimeField(auto_now_add=True)
    operationDate = models.DateTimeField(auto_now=True)
    kobilid = models.IntegerField(null=True, blank=True, default=2)

    def __str__(self):
        if self.branch == None:
            return '%s' % (self.name)
        else:
            return '%s' % (self.name + '-' + self.branch)

    class Meta:
        default_permissions = ()
        db_table = 'categoryitem'
        managed = False

sbs/models/City.py
from django.db import models


class City(models.Model):
    name = models.TextField(blank=True, null=True, verbose_name='Şehir')
    plateNo = models.IntegerField()

    def __str__(self):
        return '%s' % self.name

    def save(self, force_insert=False, force_update=False):
        self.name = self.name.upper()
        super(City, self).save(force_insert, force_update)




    class Meta:
        default_permissions = ()
        db_table = 'city'
        # managed = False

sbs/models/Claim.py
from django.db import models


class Claim(models.Model):
    WAITED = 'Beklemede'
    APPROVED = 'Onaylandı'
    PROPOUND = 'İşlem Devam Ediliyor'
    DENIED = 'Reddedildi'

    STATUS_CHOICES = (
        (APPROVED, 'Onaylandı'),
        (PROPOUND, 'İşlem Devam Ediliyor'),
        (DENIED, 'Reddedildi'),
        (WAITED, 'Beklemede'),
    )

    SBS = 'BİLGİ SİSTEMİ'
    MOBİL = 'MOBİL UYGULAMA'
    WEBSİTE = 'WEB SİTE'



    ACİL = 'ACİL'
    ONEMLİ = 'ÖNEMLİ'
    AZONEMLİ = 'AZ ÖNEMLİ'

    STATUS_PROJECT = (
        (SBS, 'BİLGİ SİSTEMİ'),
        (MOBİL, 'MOBİL UYGULAMA'),
        (WEBSİTE, 'WEB SİTE'),
    )

    İMPORTANCE = (
        (ACİL, 'ACİL'),
        (ONEMLİ, 'ÖNEMLİ'),
        (AZONEMLİ, 'AZ ÖNEMLİ'),
    )

    creationDate = models.DateTimeField(auto_now_add=True)
    modificationDate = models.DateTimeField(auto_now=True)
    # baslık
    title = models.CharField(blank=False, null=False, max_length=1000)
    # proje durumu
    project = models.CharField(max_length=128, verbose_name='Proje Seçiniz', choices=STATUS_PROJECT, default=SBS)
    # proje durumu
    status = models.CharField(max_length=128, verbose_name='Kayıt Durumu', choices=STATUS_CHOICES, default=WAITED)
    # proje açıklama
    definition = models.CharField(blank=False, null=False, max_length=1000)
    # önem durumu
    importanceSort = models.CharField(max_length=128, verbose_name='Önem Durumu', choices=İMPORTANCE, default=ACİL)
    # ücret
    pay = models.IntegerField(blank=True, null=True)

    kobilid = models.IntegerField(null=True, blank=True, default=2)

    def __str__(self):
        return '%s ' % self.title

    # class Meta:
    #     default_permissions=()

sbs/models/ClubRole.py
from django.db import models


class ClubRole(models.Model):
    name = models.TextField(blank=True, null=True, verbose_name='Kulüp Üye Rolü')
    kobilid = models.IntegerField(null=True, blank=True, default=2)

    def __str__(self):
        return '%s ' % self.name

    def save(self, force_insert=False, force_update=False):
        self.name = self.name.upper()
        super(ClubRole, self).save(force_insert, force_update)




    class Meta:
        default_permissions = ()

sbs/models/Communication.py
from django.db import models

from sbs.models.City import City
from sbs.models.Country import Country


class Communication(models.Model):
    postalCode = models.CharField(max_length=120, null=True, blank=True)
    phoneNumber = models.CharField(max_length=120, null=True, blank=True)
    phoneNumber2 = models.CharField(max_length=120, null=True, blank=True)
    address = models.TextField(blank=True, null=True, verbose_name='Adres')
    city = models.ForeignKey(City, on_delete=models.CASCADE, verbose_name='İl', db_column='city')
    country = models.ForeignKey(Country, on_delete=models.CASCADE, verbose_name='Ülke', db_column='country')
    kobilid = models.IntegerField(null=True, blank=True, default=2)

    class Meta:
        default_permissions = ()
        db_table = 'communication'
        managed = False

sbs/templates/Bolge/BolgeAdd.html
{% extends 'base_layout.html' %}
{% block content %}

    {% if messages %}
        {% for message in messages %}


            {% if message.tags == 'warning' %}

                <div class="alert alert-danger alert-dismissible">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    <h4><i class="icon fa fa-ban"></i> Hata!</h4>


                    <ul class="messages">
                        {% for message in messages %}
                            <li class="{{ message.tags }}">{{ message }}</li>
                        {% endfor %}
                    </ul>


                </div>

            {% endif %}


            {% if message.tags == 'success' %}

                <div class="alert alert-success alert-dismissible">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    <h4><i class="icon fa fa-check"></i> Başarılı!</h4>


                    <ul class="messages">
                        {% for message in messages %}
                            <li class="{{ message.tags }}">{{ message }}</li>
                        {% endfor %}
                    </ul>


                </div>

            {% endif %}
        {% endfor %}


    {% endif %}

    <section class="content-header">
        <h1>
            Bölge Ekle

        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i>Bölge Ekle</a></li>

        </ol>
    </section>
    <section class="content">

        <form method="post" enctype="multipart/form-data" role="form">
            {% csrf_token %}
            <div class="row">

                <div class="col-lg-12">
                    <div class="box box-primary">
                        <div class="box-header with-border">
                            <h3 class="box-title">BÖLGE BİLGİLERİ</h3>
                        </div>
                        <div class="box-body">
                            <div class="row">
                                <div class="col-lg-3">
                                    <div class="form-group">
                                        <label> {{ project_form.name.label }}</label>
                                        {{ project_form.name }}
                                    </div>
                                </div>
                                <div class="col-lg-3">
                                    <div class="form-group">
                                        <label> {{ project_form.type.label }}</label>
                                        {{ project_form.type }}
                                    </div>
                                </div>


                                <div class="col-lg-3">
                                    <div class="form-group">
                                        <label> {{ project_form.city.label }}</label>
                                        {{ project_form.city }}
                                    </div>
                                </div>
                                <div class="col-lg-3">
                                    <div class="form-group">
                                        <label> {{ project_form.town.label }}</label>
                                        {{ project_form.town }}
                                    </div>
                                </div>

                            </div>
                        </div>
                        <div class="box-footer">
                            <button class="btn btn-primary" type="submit">Kaydet</button>
                        </div>
                    </div>

                </div>


            </div>


        </form>


    </section>


    <script>

        $(function () {


            $("#id_city").change(function () {
                var city = $(this).find('option:selected').text();
                $("#id_town").empty();
                ilce(city);
            });

        });


        function ilce(city) {
            $.ajax({
                url: "{% url "sbs:ilce-bilgi" %}",
                type: "POST",
                data: {
                    'csrfmiddlewaretoken': "{{  csrf_token  }}",
                    "cmd": city,
                },
                success: function (result) {
                    console.log(result)

                    $("#id_town").append('<option value="">-----------</option>');
                    {#for (var i = 0, l = Object.keys(result).length; i <= l; i++) {#}
                    for (item in result.data) {
                        console.log()
                        $("#id_town").append('<option value="' + result.data[item].pk + '">' + result.data[item].name + '</option>');
                    }
                }
            });

        };


    </script>

{% endblock %}

sbs/templates/Bolge/BolgeGuncelle.html
{% extends 'base_layout.html' %}
{% block content %}

    {% if messages %}
        {% for message in messages %}


            {% if message.tags == 'warning' %}

                <div class="alert alert-danger alert-dismissible">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    <h4><i class="icon fa fa-ban"></i> Hata!</h4>


                    <ul class="messages">
                        {% for message in messages %}
                            <li class="{{ message.tags }}">{{ message }}</li>
                        {% endfor %}
                    </ul>


                </div>

            {% endif %}


            {% if message.tags == 'success' %}

                <div class="alert alert-success alert-dismissible">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    <h4><i class="icon fa fa-check"></i> Başarılı!</h4>


                    <ul class="messages">
                        {% for message in messages %}
                            <li class="{{ message.tags }}">{{ message }}</li>
                        {% endfor %}
                    </ul>


                </div>

            {% endif %}
        {% endfor %}


    {% endif %}

    <section class="content-header">
        <h1>
            Bölge Güncelle

        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i>Bölge Güncelle</a></li>

        </ol>
    </section>
    <section class="content">

        <form method="post" enctype="multipart/form-data" role="form">
            {% csrf_token %}
            <div class="row">

                <div class="col-lg-12">
                    <div class="box box-primary">
                        <div class="box-header with-border">
                            <h3 class="box-title">BÖLGE BİLGİLERİ</h3>
                        </div>
                        <div class="box-body">
                            <div class="row">
                                <div class="col-lg-3">
                                    <div class="form-group">
                                        <label> {{ project_form.name.label }}</label>
                                        {{ project_form.name }}
                                    </div>
                                </div>
                                <div class="col-lg-3">
                                    <div class="form-group">
                                        <label> {{ project_form.type.label }}</label>
                                        {{ project_form.type }}
                                    </div>
                                </div>


                                <div class="col-lg-3">
                                    <div class="form-group">
                                        <label> {{ project_form.city.label }}</label>
                                        {{ project_form.city }}
                                    </div>
                                </div>
                                <div class="col-lg-3">
                                    <div class="form-group">
                                        <label> {{ project_form.town.label }}</label>
                                        {{ project_form.town }}
                                    </div>
                                </div>

                            </div>
                        </div>
                        <div class="box-footer">
                            <button class="btn btn-primary" type="submit">Kaydet</button>
                        </div>
                    </div>

                </div>


            </div>


        </form>


    </section>


    <script>

        $(function () {


            $("#id_city").change(function () {
                var city = $(this).find('option:selected').text();
                $("#id_town").empty();
                ilce(city);
            });

        });


        function ilce(city) {
            $.ajax({
                url: "{% url "sbs:ilce-bilgi" %}",
                type: "POST",
                data: {
                    'csrfmiddlewaretoken': "{{  csrf_token  }}",
                    "cmd": city,
                },
                success: function (result) {
                    console.log(result)

                    $("#id_town").append('<option value="">-----------</option>');
                    {#for (var i = 0, l = Object.keys(result).length; i <= l; i++) {#}
                    for (item in result.data) {
                        $("#id_town").append('<option value="' + result.data[item].pk + '">' + result.data[item].name + '</option>');
                    }
                }
            });

        };


    </script>

{% endblock %}