sbs/urls.py
from django.conf.urls import url
from django.urls import path, include
from rest_framework.routers import DefaultRouter

from sbs.Views import DashboardViews, AthleteViews, RefereeViews, ClubViews, CoachViews, DirectoryViews, UserViews, \
    CompetitionViews, AdminViews, HelpViews, PageViews, PreRegistration, EPProjectViews, EmployeeViews, PdfView, \
    TechnicalViews, LogViews, NotificationView, CompanyView, ClaimView, GtasinamazView
from sbs.api.message import UserModelViewSet, MessageModelViewSet, UserModelEndMessageViewSet, EmployeModelViewSet, \
    CompanyModelViewSet

app_name = 'sbs'

router = DefaultRouter()
router.register(r'mesaj', MessageModelViewSet, basename='message-api')
router.register(r'kul', UserModelViewSet, basename='user-api')
router.register(r'kulEndMessage', UserModelEndMessageViewSet, basename='user-api-end')
router.register(r'employess', EmployeModelViewSet, basename='employee-api')
router.register(r'company', CompanyModelViewSet, basename='company-api')



urlpatterns = [

    # Dashboard
    url(r'anasayfa/admin/$', DashboardViews.return_admin_dashboard, name='admin'),
    url(r'anasayfa/sehir-sporcu-sayisi/$', DashboardViews.City_athlete_cout, name='sehir-sporcu-sayisi'),
    url(r'anasayfa/sporcu/$', DashboardViews.return_athlete_dashboard, name='sporcu'),
    url(r'anasayfa/hakem/$', DashboardViews.return_referee_dashboard, name='hakem'),
    url(r'anasayfa/antrenor/$', DashboardViews.return_coach_dashboard, name='antrenor'),
    url(r'anasayfa/yonetim/$', DashboardViews.return_directory_dashboard, name='federasyon'),
    url(r'anasayfa/kulup-uyesi/$', DashboardViews.return_club_user_dashboard, name='kulup-uyesi'),

    # Sporcular
    url(r'sporcu/sporcu-ekle/$', AthleteViews.return_add_athlete, name='sporcu-ekle'),
    url(r'sporcu/sporcular/$', AthleteViews.return_athletes, name='sporcular'),

    # pagenation deneme
    url(r'page/$', PageViews.deneme, name='deneme'),
    url(r'sporcularajax/$', PageViews.return_athletesdeneme, name='sporculardeneme'),

    url(r'sporcu/sporcuKusakEkle/(?P<pk>\d+)$', AthleteViews.sporcu_kusak_ekle, name='sporcu-kusak-ekle'),
    url(r'sporcu/sporcuKusakDuzenle/(?P<belt_pk>\d+)/(?P<athlete_pk>\d+)$', AthleteViews.sporcu_kusak_duzenle,
        name='sporcu-kusak-duzenle'),
    url(r'sporcu/sporcuLisansEkle/(?P<pk>\d+)$', AthleteViews.sporcu_lisans_ekle, name='sporcu-lisans-ekle'),
    url(r'sporcu/sporcuLisansDuzenle/(?P<license_pk>\d+)/(?P<athlete_pk>\d+)$', AthleteViews.sporcu_lisans_duzenle,
        name='sporcu-lisans-duzenle'),
    url(r'sporcu/sporcuLisansDuzenleMobil/(?P<count>\d+)$', AthleteViews.sporcu_lisans_duzenle_mobil,
        name='sporcu-lisans-duzenle-mobil'),
    # ilk degeri verebilmek icin yönlendirme amaci ile kullanildi.
    url(r'sporcu/sporcuLisansDuzenleMobil/$', AthleteViews.sporcu_lisans_duzenle_mobil_ilet,
        name='sporcu-lisans-duzenle-mobil-ilet'),

    url(r'sporcu/sporcuLisansDuzenle/onayla/(?P<license_pk>\d+)/(?P<athlete_pk>\d+)$',
        AthleteViews.sporcu_lisans_onayla, name='sporcu-lisans-onayla'),

    url(r'sporcu/sporcuLisansDuzenle/reddet/(?P<license_pk>\d+)/(?P<athlete_pk>\d+)$',
        AthleteViews.sporcu_lisans_reddet, name='sporcu-lisans-reddet'),
    url(r'sporcu/sporcuLisansDuzenle/lisanssil/(?P<pk>\d+)/(?P<athlete_pk>\d+)$', AthleteViews.sporcu_lisans_sil,
        name='sporcu-lisans-sil'),
    url(r'sporcu/sporcuLisansListesi/onayla/(?P<license_pk>\d+)$',
        AthleteViews.sporcu_lisans_listesi_onayla, name='sporcu-lisans-listesi-onayla'),
    url(r'sporcu/sporcuLisansListesi/onaylaMobil/(?P<license_pk>\d+)/(?P<count>\d+)$',
        AthleteViews.sporcu_lisans_listesi_onayla_mobil, name='sporcu-lisans-listesi-onayla-mobil'),
    # lisans listesinin hepsini onaylama
    url(r'sporcu/sporcuLisansListesi/hepsinionayla/$', AthleteViews.sporcu_lisans_listesi_hepsionay,
        name='sporcu-lisans-hepsini-onayla'),
    # lisanslarin hepsini reddetme
    url(r'sporcu/sporcuLisansListesi/hepsiniReddet/$', AthleteViews.sporcu_lisans_listesi_hepsireddet,
        name='sporcu-lisans-hepsini-reddet'),

    # hepsini beklemeye al
    url(r'sporcu/sporcuLisansListesi/hepsinibekle/$', AthleteViews.sporcu_bekle,
        name='sporcu-lisans-hepsini-bekle'),

    url(r'sporcu/sporcuLisansListesi/reddet/(?P<license_pk>\d+)$',
        AthleteViews.sporcu_lisans_listesi_reddet, name='sporcu-lisans-listesi-reddet'),
    url(r'sporcu/sporcuLisansListesiMobil/reddet/(?P<license_pk>\d+)/(?P<count>\d+)$',
        AthleteViews.sporcu_lisans_listesi_reddet_mobil, name='sporcu-lisans-listesi-reddet-mobil'),
    url(r'sporcu/kusak/$', AthleteViews.return_belt, name='kusak'),
    url(r'sporcu/kusak/sil/(?P<pk>\d+)$', AthleteViews.categoryItemDelete,
        name='categoryItem-delete'),
    url(r'sporcu/kusakDuzenle/(?P<pk>\d+)$', AthleteViews.categoryItemUpdate,
        name='categoryItem-duzenle'),
    url(r'sporcu/sporcuKusakDuzenle/onayla/(?P<belt_pk>\d+)/(?P<athlete_pk>\d+)$',
        AthleteViews.sporcu_kusak_onayla, name='sporcu-kusak-onayla'),
    url(r'sporcu/sporcuKusakReddet/(?P<belt_pk>\d+)/(?P<athlete_pk>\d+)$',
        AthleteViews.sporcu_kusak_reddet, name='sporcu-kusak-reddet'),
    url(r'sporcu/sporcuKusakDuzenle/kusaksil/(?P<pk>\d+)/(?P<athlete_pk>\d+)$', AthleteViews.sporcu_kusak_sil,
        name='sporcu-kusak-sil'),

    # kuşaklarin hepsini beklemeye al
    url(r'sporcu/sporcuKusakbekle',
        AthleteViews.sporcu_kusak_bekle, name='sporcu-kusak-bekle'),
    # kuşak listesinin hepsini onayla
    url(r'sporcu/sporcuKusakListesi/hepsinionayla/$',
        AthleteViews.sporcu_kusak_listesi_hepsinionayla, name='sporcu-kusak-listesi-hepsinionayla'),

    # kuşak hepsini reddet
    url(r'sporcu/sporcuKusakDuzenle/reddet/$',
        AthleteViews.sporcu_kusak_hepsinireddet, name='sporcu-kusak-hepsinireddet'),

    # kusak listesi onay
    url(r'sporcu/sporcuKusakListesi/onayla/(?P<belt_pk>\d+)$',
        AthleteViews.sporcu_kusak_listesi_onayla, name='sporcu-kusak-listesi-onayla'),
    # kuşak listesi reddet
    url(r'sporcu/sporcuKusakListesi/reddet/(?P<belt_pk>\d+)$',
        AthleteViews.sporcu_kusak_listesi_reddet, name='sporcu-kusak-listesi-reddet'),

    url(r'sporcu/sporcuDuzenle/(?P<pk>\d+)$', AthleteViews.updateathletes, name='update-athletes'),
    url(r'sporcu/sporcu-kusak-listesi/$', AthleteViews.sporcu_kusak_listesi, name='kusak-listesi'),
    url(r'sporcu/sporcu-lisans-listesi/$', AthleteViews.sporcu_lisans_listesi, name='lisans-listesi'),
    url(r'sporcu/sporcu-profil-guncelle/$', AthleteViews.updateAthleteProfile,
        name='sporcu-profil-guncelle'),

    # Hakemler
    url(r'hakem/hakem-ekle/$', RefereeViews.return_add_referee, name='hakem-ekle'),
    url(r'hakem/hakemler/$', RefereeViews.return_referees, name='hakemler'),
    url(r'hakem/seviye/$', RefereeViews.return_level, name='seviye'),
    url(r'hakem/seviye/sil/(?P<pk>\d+)$', RefereeViews.categoryItemDelete,
        name='categoryItem-delete-seviye'),
    url(r'hakem/seviye/(?P<pk>\d+)$', RefereeViews.categoryItemUpdate,
        name='categoryItem-duzenle-seviye'),
    url(r'hakem/hakemler/sil/(?P<pk>\d+)$', RefereeViews.deleteReferee,
        name='referee-delete'),
    url(r'hakem/hakemDuzenle/(?P<pk>\d+)$', RefereeViews.updateReferee,
        name='hakem-duzenle'),
    url(r'hakem/hakem-profil-guncelle/$', RefereeViews.updateRefereeProfile,
        name='hakem-profil-guncelle'),
    # /kademe
    url(r'hakem/Hakem-kademe-ekle/(?P<pk>\d+)$', RefereeViews.hakem_kademe_ekle, name='hakem-kademe-ekle'),
    url(r'hakem/Kademe-Duzenle/onayla/(?P<grade_pk>\d+)/(?P<referee_pk>\d+)$', RefereeViews.kademe_onay,
        name='kademe-onayla-hakem'),
    url(r'hakem/Kademe-Duzenle/reddet/(?P<grade_pk>\d+)/(?P<referee_pk>\d+)$', RefereeViews.kademe_reddet,
        name='kademe-reddet-hakem'),
    url(r'hakem/Kademe-Duzenle/güncelle/(?P<grade_pk>\d+)/(?P<referee_pk>\d+)$', RefereeViews.kademe_update,
        name='kademe-güncelle-hakem'),
    url(r'hakem/Kademe-Duzenle/sil/(?P<grade_pk>\d+)/(?P<referee_pk>\d+)$', RefereeViews.kademe_delete,
        name='Kademe-sil-hakem'),
    # /vize
    url(r'hakem/hakem-vize-ekle/(?P<pk>\d+)$', RefereeViews.vısa_ekle, name='hakem-vize-ekle'),
    url(r'hakem/Vize-Duzenle/onayla/(?P<grade_pk>\d+)/(?P<referee_pk>\d+)$', RefereeViews.visa_onay,
        name='hakem-vize-onayla'),
    url(r'hakem/Vize-Duzenle/reddet/(?P<grade_pk>\d+)/(?P<referee_pk>\d+)$', RefereeViews.visa_reddet,
        name='hakem-vize-reddet'),
    url(r'hakem/Vize-Duzenle/guncelle/(?P<grade_pk>\d+)/(?P<referee_pk>\d+)$', RefereeViews.vize_update,
        name='hakem-vize-güncelle'),
    url(r'hakem/Vize-Duzenle/sil/(?P<grade_pk>\d+)/(?P<referee_pk>\d+)$', RefereeViews.vize_delete,
        name='hakem-vize-sil'),

    # Kulüpler
    url(r'kulup/basvuru-listesi/$', PreRegistration.return_preRegistration, name='basvuru-listesi'),
    url(r'kulup/basvuru/onayla/(?P<pk>\d+)$', PreRegistration.approve_preRegistration, name='basvuru-onayla'),
    url(r'kulup/basvuru/reddet/(?P<pk>\d+)$', PreRegistration.rejected_preRegistration, name='basvuru-reddet'),
    url(r'sporcu/basvuru-incele/(?P<pk>\d+)$', PreRegistration.update_preRegistration, name='update-basvuru'),

    url(r'kulup/kulup-ekle/$', ClubViews.return_add_club, name='kulup-ekle'),
    url(r'kulup/kulupler/$', ClubViews.return_clubs, name='kulupler'),
    url(r'kulup/kulup-uyesi-ekle/$', ClubViews.return_add_club_person, name='kulup-uyesi-ekle'),
    url(r'kulup/kulup-uyesi-guncelle/(?P<pk>\d+)$', ClubViews.updateClubPersons, name='kulup-uyesi-guncelle'),
    url(r'kulup/kulup-uyeleri/$', ClubViews.return_club_person, name='kulup-uyeleri'),
    url(r'kulup/kulup-uye-rolu/$', ClubViews.return_club_role, name='kulup-uye-rolu'),
    url(r'kulup/kulup-uye-rolu/sil/(?P<pk>\d+)$', ClubViews.deleteClubRole,
        name='ClubRole-delete'),
    url(r'kulup/kulup-uyeleri/sil/(?P<pk>\d+)$', ClubViews.deleteClubUser,
        name='ClubUser-delete'),

sbs/models/Athlete.py
from django.contrib.auth.models import User
from django.db import models

from sbs.models.Communication import Communication
from sbs.models.Level import Level
from sbs.models.License import License
from sbs.models.Person import Person


class Athlete(models.Model):
    person = models.OneToOneField(Person, on_delete=models.CASCADE, db_column='person')
    communication = models.OneToOneField(Communication, on_delete=models.CASCADE, db_column='communication')
    user = models.OneToOneField(User, on_delete=models.CASCADE, db_column='user')
    belts = models.ManyToManyField(Level)
    licenses = models.ManyToManyField(License)
    creationDate = models.DateTimeField(auto_now_add=True)
    operationDate = models.DateTimeField(auto_now=True)
    kobilid = models.IntegerField(null=True, blank=True, default=2)

    def __str__(self):
        return '%s %s' % (self.user.first_name, self.user.last_name)

    class Meta:
        ordering = ['pk']
        default_permissions = ()
        db_table = 'athlete'
        managed = False

sbs/models/BeltExam.py
from django.db import models

from sbs.models import Coach, Athlete, SportsClub
from sbs.models.EnumFields import EnumFields


class BeltExam(models.Model):
    BANK = 'Banka'
    POSTA = 'Posta'
    PAYMENT_CHOICES = (
        (BANK, 'Banka'),
        (POSTA, 'Posta'),
    )
    WAITED = 'Beklemede'
    APPROVED = 'Onaylandı'
    PROPOUND = 'Onaya Gönderildi'
    DENIED = 'Reddedildi'

    STATUS_CHOICES = (
        (APPROVED, 'Onaylandı'),
        (PROPOUND, 'Onaya Gönderildi'),
        (DENIED, 'Reddedildi'),
        (WAITED, 'Beklemede'),
    )

    creationDate = models.DateTimeField(auto_now_add=True)
    modificationDate = models.DateTimeField(auto_now=True)
    examDate = models.DateField(null=False, blank=False)

    coachs=models.ManyToManyField(Coach)


    paymentType = models.CharField(max_length=128, verbose_name='Ödeme Şekli', choices=PAYMENT_CHOICES, default=BANK)
    dekont = models.FileField(upload_to='dekont/', null=False, blank=False, verbose_name='Dekont ')
    dekontDate = models.DateField(null=True, blank=True)
    dekontDescription = models.CharField(max_length=255, null=True, blank=True)
    athletes = models.ManyToManyField(Athlete)
    status = models.CharField(max_length=128, verbose_name='Onay Durumu', choices=STATUS_CHOICES, default=WAITED)
    sportClub = models.ForeignKey(SportsClub, on_delete=models.CASCADE, null=False, blank=False)
    description = models.CharField(max_length=255, null=True, blank=True)
    branch = models.CharField(max_length=128, choices=EnumFields.BRANCH.value, null=False, blank=False)
    kobilid = models.IntegerField(null=True, blank=True, default=2)


    class Meta:
        default_permissions = ()

sbs/models/Branch.py
from django.db import models


class Branch(models.Model):
    name = models.CharField(blank=True, null=True, max_length=120, verbose_name='Branş Adı')
    creationDate = models.DateTimeField(auto_now_add=True)
    modificationDate = models.DateTimeField(auto_now=True)
    kobilid = models.IntegerField(null=True, blank=True, default=2)

    def __str__(self):
        return '%s ' % self.name

    class Meta:
        default_permissions = ()

sbs/models/CategoryItem.py
from django.db import models

from sbs.models.EnumFields import EnumFields


class CategoryItem(models.Model):
    name = models.CharField(blank=False, null=False, max_length=255)
    forWhichClazz = models.CharField(blank=False, null=False, max_length=255)
    parent = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True)
    branch = models.CharField(max_length=128, choices=EnumFields.BRANCH.value,null=True,blank=True,verbose_name='Seçiniz')
    isFirst = models.BooleanField()
    creationDate = models.DateTimeField(auto_now_add=True)
    operationDate = models.DateTimeField(auto_now=True)
    kobilid = models.IntegerField(null=True, blank=True, default=2)

    def __str__(self):
        if self.branch == None:
            return '%s' % (self.name)
        else:
            return '%s' % (self.name + '-' + self.branch)

    class Meta:
        default_permissions = ()
        db_table = 'categoryitem'
        managed = False

sbs/models/City.py
from django.db import models


class City(models.Model):
    name = models.TextField(blank=True, null=True, verbose_name='Şehir')
    plateNo = models.IntegerField()

    def __str__(self):
        return '%s' % self.name

    def save(self, force_insert=False, force_update=False):
        self.name = self.name.upper()
        super(City, self).save(force_insert, force_update)




    class Meta:
        default_permissions = ()
        db_table = 'city'
        # managed = False

sbs/models/Claim.py
from django.db import models


class Claim(models.Model):
    WAITED = 'Beklemede'
    APPROVED = 'Onaylandı'
    PROPOUND = 'İşlem Devam Ediliyor'
    DENIED = 'Reddedildi'

    STATUS_CHOICES = (
        (APPROVED, 'Onaylandı'),
        (PROPOUND, 'İşlem Devam Ediliyor'),
        (DENIED, 'Reddedildi'),
        (WAITED, 'Beklemede'),
    )

    SBS = 'BİLGİ SİSTEMİ'
    MOBİL = 'MOBİL UYGULAMA'
    WEBSİTE = 'WEB SİTE'



    ACİL = 'ACİL'
    ONEMLİ = 'ÖNEMLİ'
    AZONEMLİ = 'AZ ÖNEMLİ'

    STATUS_PROJECT = (
        (SBS, 'BİLGİ SİSTEMİ'),
        (MOBİL, 'MOBİL UYGULAMA'),
        (WEBSİTE, 'WEB SİTE'),
    )

    İMPORTANCE = (
        (ACİL, 'ACİL'),
        (ONEMLİ, 'ÖNEMLİ'),
        (AZONEMLİ, 'AZ ÖNEMLİ'),
    )

    creationDate = models.DateTimeField(auto_now_add=True)
    modificationDate = models.DateTimeField(auto_now=True)
    # baslık
    title = models.CharField(blank=False, null=False, max_length=1000)
    # proje durumu
    project = models.CharField(max_length=128, verbose_name='Proje Seçiniz', choices=STATUS_PROJECT, default=SBS)
    # proje durumu
    status = models.CharField(max_length=128, verbose_name='Kayıt Durumu', choices=STATUS_CHOICES, default=WAITED)
    # proje açıklama
    definition = models.CharField(blank=False, null=False, max_length=1000)
    # önem durumu
    importanceSort = models.CharField(max_length=128, verbose_name='Önem Durumu', choices=İMPORTANCE, default=ACİL)
    # ücret
    pay = models.IntegerField(blank=True, null=True)

    kobilid = models.IntegerField(null=True, blank=True, default=2)

    def __str__(self):
        return '%s ' % self.title

    # class Meta:
    #     default_permissions=()

sbs/models/ClubRole.py
from django.db import models


class ClubRole(models.Model):
    name = models.TextField(blank=True, null=True, verbose_name='Kulüp Üye Rolü')
    kobilid = models.IntegerField(null=True, blank=True, default=2)

    def __str__(self):
        return '%s ' % self.name

    def save(self, force_insert=False, force_update=False):
        self.name = self.name.upper()
        super(ClubRole, self).save(force_insert, force_update)




    class Meta:
        default_permissions = ()

sbs/models/Coach.py
from django.contrib.auth.models import User
from django.db import models

from sbs.models.Level import Level
from sbs.models.Communication import Communication
from sbs.models.Person import Person


class Coach(models.Model):
    person = models.OneToOneField(Person, on_delete=models.CASCADE)
    communication = models.OneToOneField(Communication, on_delete=models.CASCADE)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    grades = models.ManyToManyField(Level, related_name='CoachGrades')
    visa = models.ManyToManyField(Level, related_name='CoachVisa')
    creationDate = models.DateTimeField(auto_now_add=True)
    modificationDate = models.DateTimeField(auto_now=True)

    def __str__(self):
        return '%s %s' % (self.user.first_name, self.user.last_name)

    class Meta:
        ordering = ['pk']
        default_permissions = ()

sbs/templates/kulup/kulup-uye-rolu.html
{% extends 'base_layout.html' %}
{% block content %}


    <!-- success modal -->
    <div class="modal modal-success modal-success-food fade in" id="modal-success" style="display: none;">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span></button>
                    <h4 class="modal-title">İşlem Başarılı</h4>
                </div>
                <div class="modal-body successModal">
                    ...
                </div>
                <div class="modal-footer">

                    <button type="button" class="btn btn-outline btn-ok">Tamam</button>
                </div>
            </div>
            <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
    </div>

    <div class="modal modal-danger fade in deneme22" tabindex="-1" role="dialog" id="modal-danger"
         aria-hidden="true" style="display: none;">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span></button>
                    <h4 class="modal-title">Uyarı</h4>
                </div>
                <div class="modal-body">
                    <p>Silmek istediğinizden emin misiniz?</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-outline pull-left btn-ok" id="btn-conf"
                            data-dismiss="modal">Evet
                    </button>
                    <button type="button" class="btn btn-outline" id="btn-close">Hayır</button>
                </div>
            </div>
            <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
    </div>



    {% if messages %}
        {% for message in messages %}


            {% if message.tags == 'warning' %}

                <div class="alert alert-danger alert-dismissible">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    <h4><i class="icon fa fa-ban"></i> Hata!</h4>


                    <ul class="messages">
                        {% for message in messages %}
                            <li class="{{ message.tags }}">{{ message }}</li>
                        {% endfor %}
                    </ul>


                </div>

            {% endif %}


            {% if message.tags == 'success' %}

                <div class="alert alert-success alert-dismissible">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    <h4><i class="icon fa fa-check"></i> Başarılı!</h4>


                    <ul class="messages">
                        {% for message in messages %}
                            <li class="{{ message.tags }}">{{ message }}</li>
                        {% endfor %}
                    </ul>


                </div>

            {% endif %}
        {% endfor %}


    {% endif %}

    <section class="content">

        <!-- /.row -->
        <!-- Main row -->
        <div class="row">


            <section class="col-lg-12 ">


                <div class="box-body">


                    <div class="box box-primary">
                        <div class="box-header with-border">
                            <h3 class="box-title">Kulüp Üye Rolleri</h3>
                        </div>
                        <!-- /.box-header -->
                        <!-- form start -->
                        <form method="post" role="form">
                            <div class="box-body">
                                {% csrf_token %}


                                <div class="form-group">
                                    <label> {{ club_role_form.name.label }}</label>
                                    {{ club_role_form.name }}
                                </div>


                            </div>
                            <!-- /.box-body -->

                            <div class="box-footer">
                                <button type="submit" class="btn btn-primary">Kaydet</button>
                            </div>
                        </form>


                        <table id="kategori" class="table table-bordered table-hover">
                            <thead>
                            <tr>
                                <th>No</th>
                                <th>Kuşak Adı</th>
                                <th>Güncelleme/Silme</th>

                            </tr>
                            </thead>

                            <tbody>


                            {% if club_role.all %}
                                {% for clubRole in club_role %}
                                    <tr>
                                        <td>{{ forloop.counter }} </td>
                                        <td>{{ clubRole.name }}</td>
                                        <td>
                                            <div class="btn-group">
                                                <a href="{% url "sbs:updateClubRole" clubRole.pk %}"
                                                   type="button" class="btn btn-warning"><i
                                                        class="fa fa-edit"></i>Güncelle
                                                </a>

                                                <a class="btn btn-danger"
                                                   data-toggle="modal" onclick=deleteClubRole({{ clubRole.pk }})><i
                                                        class="fa fa-trash"></i>Sil</a>
                                            </div>
                                        </td>

                                    </tr>

                                {% endfor %}
                            {% endif %}


                            </tbody>
                        </table>


                    </div>
                    <!-- /.box -->


                </div>
            </section>


        </div>
        <!-- /.row (main row) -->

    </section>



    <script>
        $(function () {
            $('#kategori').DataTable({
                'paging': false,
                'lengthChange': false,
                'searching': false,
                'ordering': false,
                'info': false,
                'autoWidth': true
            })

        })
    </script>


    <script>
        function deleteClubRole(id) {

            console.log(id);
            var html = ''
            $("#modal-danger").on("shown.bs.modal", function (e) {
                $("#btn-conf").click(function () {
                    $.ajax({
                        url: "{% url "sbs:ClubRole-delete" pk=212121223232323232 %}".replace(/212121223232323232/, id.toString()),
                        type: "POST",
                        data: {
                            'csrfmiddlewaretoken': "{{  csrf_token  }}",
                            isActive: 'False'
                        },
                        success: function (result) {

                            html = 'Kulüp Rolü Başarıyla Silindi';
                            debugger;
                            $(".successModal").html(html);
                            $('#modal-success').on("shown.bs.modal", function (e) {
                                $(".btn-ok").click(function () {

                                    window.location.replace("{% url "sbs:kulup-uye-rolu" %}");

                                });

                            }).modal('show');


                            console.log(result.status)
                        }
                    });
                });
            }).modal('show');
            $('#btn-close').click(function () {
                $('#modal-danger').modal('hide');
            });

        }
    </script>






{% endblock %}